services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  cf-miner:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - TARGET_URL=${TARGET_URL}
    command:
      - poetry run python src/main.py
    depends_on:
      - redis
