services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  cf-miner:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - TARGET_URL=${TARGET_URL}
    volumes:
      - screenshots:/app/screenshots
    command: >
      sh -c "Xvfb :99 -ac -screen 0 1920x1080x24 & 
      export DISPLAY=:99 && 
      python -m src.main"
    depends_on:
      - redis

volumes:
  screenshots: